# Generated by cailoxo. Do not edit by hand.
# shell: zsh

if [[ -o interactive ]]; then
  autoload -Uz add-zsh-hook

  typeset -g __CAILOXO_OS_TEMPLATE=' {{ icon }} '
  typeset -g __CAILOXO_PATH_TEMPLATE=' {{ if home }} {{ else }} {{ end }}{{ path }} '
  typeset -g __CAILOXO_GIT_TEMPLATE=' {{ upstream_icon }}{{ branch_icon }}{{ branch }}{{ if status }} {{ status }}{{ end }} '
  typeset -g __CAILOXO_PROMPT_TEMPLATE='   '
  typeset -g __CAILOXO_TRANSIENT_TEMPLATE=' '
  typeset -g __CAILOXO_HOME_ICON='~'
  typeset -g __CAILOXO_FOLDER_ICON='…'
  typeset -g __CAILOXO_EDGE_FORMAT='<b>%s</b>'
  typeset -g __CAILOXO_GITDIR_FORMAT='<b><i>%s</i></b>'
  typeset -g __CAILOXO_BRANCH_ICON=' '
  typeset -g __CAILOXO_STATUS_SEPARATOR=' '
  typeset -gi __CAILOXO_GIT_STATUS=1
  typeset -gi __CAILOXO_FETCH_UPSTREAM_ICON=1
  typeset -gi __CAILOXO_GIT_URL=1
  typeset -gi __CAILOXO_FETCH_REMOTE=1
  typeset -gi __CAILOXO_FETCH_REMOTE_INTERVAL_S=60
  typeset -gi __CAILOXO_FETCH_REMOTE_TIMEOUT_S=5
  typeset -gi __CAILOXO_MIN_DIRS=1
  typeset -gi __CAILOXO_FINAL_SPACE=1
  typeset -gi __CAILOXO_PATH_URL=1
  typeset -gi __CAILOXO_OSC7=1
  typeset -g __CAILOXO_OS_STYLE=$'\e[38;5;0m\e[48;5;7m'
  typeset -g __CAILOXO_PATH_STYLE=$'\e[38;5;0m\e[48;5;4m'
  typeset -g __CAILOXO_GIT_CLEAN_STYLE=$'\e[38;5;0m\e[48;5;2m'
  typeset -g __CAILOXO_GIT_DIRTY_STYLE=$'\e[38;5;0m\e[48;5;3m'
  typeset -g __CAILOXO_RESET=$'\e[0m'
  typeset -g __CAILOXO_OS_TAIL=$'%{\e[38;5;7m\e[48;5;4m%}%{\e[0m%}'
  typeset -g __CAILOXO_PATH_SEP_CLEAN=$'%{\e[38;5;4m\e[48;5;2m%}%{\e[0m%}'
  typeset -g __CAILOXO_PATH_SEP_DIRTY=$'%{\e[38;5;4m\e[48;5;3m%}%{\e[0m%}'
  typeset -g __CAILOXO_PATH_SEP_LAST=$'%{\e[38;5;4m%}%{\e[0m%}'
  typeset -g __CAILOXO_GIT_SEP_CLEAN=$'%{\e[38;5;2m%}%{\e[0m%}'
  typeset -g __CAILOXO_GIT_SEP_DIRTY=$'%{\e[38;5;3m%}%{\e[0m%}'
  typeset -g __CAILOXO_PROMPT_OK_STYLE=$'\e[38;5;2m'
  typeset -g __CAILOXO_PROMPT_ERROR_STYLE=$'\e[38;5;1m'
  typeset -g __CAILOXO_TRANSIENT_OK_STYLE=$'\e[38;5;2m'
  typeset -g __CAILOXO_TRANSIENT_ERROR_STYLE=$'\e[38;5;1m'

  __cailoxo_pansi() {
    print -nr -- "%{${1}%}"
  }

  __cailoxo_style_template() {
    local text=$1
    local bold_on bold_off italic_on italic_off
    bold_on=$(__cailoxo_pansi $'\e[1m')
    bold_off=$(__cailoxo_pansi $'\e[22m')
    italic_on=$(__cailoxo_pansi $'\e[3m')
    italic_off=$(__cailoxo_pansi $'\e[23m')
    text=${text//'<b>'/$bold_on}
    text=${text//'<\/b>'/$bold_off}
    text=${text//'<i>'/$italic_on}
    text=${text//'<\/i>'/$italic_off}

    print -r -- "$text"
  }

  __cailoxo_plain_template() {
    local text=$1
    text=${text//'<b>'/}
    text=${text//'<\/b>'/}
    text=${text//'<i>'/}
    text=${text//'<\/i>'/}

    print -r -- "$text"
  }

  __cailoxo_url_escape() {
    local value=${1//\\//}
    value=${value//\%/%25}
    value=${value// /%20}
    value=${value//\#/%23}
    value=${value//\?/%3F}
    value=${value//\;/%3B}
    print -r -- "$value"
  }

  __cailoxo_file_url() {
    local path=$(__cailoxo_url_escape "$PWD") host=${HOST:-$(hostname 2>/dev/null)}
    if [[ $path == [[:alpha:]]:/* ]]; then
      print -r -- "file:///$path"
    else
      print -r -- "file://$host$path"
    fi
  }

  __cailoxo_osc7() {
    (( __CAILOXO_OSC7 )) || return
    local url=$(__cailoxo_file_url)
    [[ -n $url ]] && __cailoxo_pansi $'\e]7;'"$url"$'\e\\'
  }

  __cailoxo_path_url_start() {
    (( __CAILOXO_PATH_URL )) || return
    local url=$(__cailoxo_file_url)
    [[ -n $url ]] && __cailoxo_pansi $'\e]8;;'"$url"$'\e\\'
  }

  __cailoxo_path_url_end() {
    (( __CAILOXO_PATH_URL )) || return
    __cailoxo_pansi $'\e]8;;\e\\'
  }

  __cailoxo_format_part() {
    local value=$1 format=$2
    [[ -n $format ]] || { print -r -- "$value"; return }
    [[ $format == *%s* ]] || { print -r -- "$value"; return }
    print -r -- "${format//\%s/$value}"
  }

  __cailoxo_git_root_name() {
    local root
    root=$(git rev-parse --show-toplevel 2>/dev/null) || return
    print -r -- "${root:t}"
  }

  __cailoxo_format_path() {
    local input=$1 git_root=$2 prefix= rest absolute=0
    if [[ $input == '~' ]]; then
      __cailoxo_format_part "$input" "$__CAILOXO_EDGE_FORMAT"
      return
    elif [[ $input == '~/'* ]]; then
      prefix='~'
      rest=${input#\~/}
    elif [[ $input == '…/'* ]]; then
      prefix='…'
      rest=${input#…/}
    elif [[ $input == /* ]]; then
      absolute=1
      rest=${input#/}
    else
      rest=$input
    fi

    local -a raw_parts parts out
    raw_parts=("${(@s:/:)rest}")
    local part
    for part in "${raw_parts[@]}"; do
      [[ -n $part ]] && parts+=("$part")
    done

    if (( absolute )) && (( ${#parts} == 0 )); then
      __cailoxo_format_part / "$__CAILOXO_EDGE_FORMAT"
      return
    fi

    if [[ -n $prefix ]]; then
      if [[ $prefix == '…' ]]; then
        out+=("$prefix")
      else
        out+=("$(__cailoxo_format_part "$prefix" "$__CAILOXO_EDGE_FORMAT")")
      fi
    fi

    local i raw
    for (( i = 1; i <= ${#parts}; i++ )); do
      raw=$parts[$i]
      part=$raw
      if [[ -n $git_root && $raw == $git_root ]]; then
        part=$(__cailoxo_format_part "$part" "$__CAILOXO_GITDIR_FORMAT")
      fi
      if (( i == ${#parts} || (i == 1 && ${#out} == 0) )); then
        part=$(__cailoxo_format_part "$part" "$__CAILOXO_EDGE_FORMAT")
      fi
      out+=("$part")
    done

    local joined=${(j:/:)out}
    (( absolute )) && joined="/$joined"
    print -r -- "$joined"
  }

  __cailoxo_os_icon() {
    local id=unknown
    if [[ -r /etc/os-release ]]; then
      local line
      while IFS='=' read -r key value; do
        [[ $key == ID ]] || continue
        id=${value//\"/}
        break
      done < /etc/os-release
    elif [[ $OSTYPE == darwin* ]]; then
      id=macos
    elif [[ $OSTYPE == msys* || $OSTYPE == cygwin* ]]; then
      id=windows
    fi

    case ${id:l} in
      alpine) print -r -- '' ;;
      android) print -r -- '' ;;
      arch) print -r -- '' ;;
      centos) print -r -- '' ;;
      debian) print -r -- '' ;;
      fedora) print -r -- '' ;;
      freebsd) print -r -- '' ;;
      gentoo) print -r -- '' ;;
      linux) print -r -- '' ;;
      linux_mint) print -r -- '󰣭' ;;
      macos) print -r -- '' ;;
      manjaro) print -r -- '' ;;
      nixos) print -r -- '' ;;
      opensuse) print -r -- '' ;;
      raspbian) print -r -- '' ;;
      redhat) print -r -- '󱄛' ;;
      ubuntu) print -r -- '' ;;
      unknown) print -r -- '' ;;
      windows) print -r -- '' ;;
      wsl) print -r -- '' ;;
      *) print -r -- '' ;;
    esac
  }

  __cailoxo_upstream_provider() {
    local url=${1:l}
    if [[ $url == *github.com* ]]; then print -r -- github
    elif [[ $url == *gitlab.com* ]]; then print -r -- gitlab
    elif [[ $url == *bitbucket.org* ]]; then print -r -- bitbucket
    elif [[ $url == *codeberg.org* ]]; then print -r -- codeberg
    elif [[ $url == *gitea* ]]; then print -r -- gitea
    elif [[ $url == *dev.azure.com* || $url == *visualstudio.com* ]]; then print -r -- azure_devops
    fi
  }

  __cailoxo_clean_git_url() {
    local url=$1 rest host path
    [[ -n $url ]] || return
    url=${url%/}
    url=${url%.git}

    if [[ $url == http://* || $url == https://* ]]; then
      print -r -- "$url"
      return
    fi

    if [[ $url == git@ssh.dev.azure.com:v3/* ]]; then
      path=${url#git@ssh.dev.azure.com:v3/}
      local -a parts
      parts=(${(s:/:)path})
      if (( ${#parts} >= 3 )); then
        print -r -- "https://dev.azure.com/$parts[1]/$parts[2]/_git/$parts[3]"
        return
      fi
    fi

    if [[ $url == *://* ]]; then
      rest=${url#*://}
      rest=${rest#*@}
      host=${rest%%/*}
      path=${rest#*/}
      host=${host%%:*}
      if [[ $host == ssh.dev.azure.com && $path == v3/* ]]; then
        local -a parts
        parts=(${(s:/:)path})
        if (( ${#parts} >= 4 )); then
          print -r -- "https://dev.azure.com/$parts[2]/$parts[3]/_git/$parts[4]"
          return
        fi
      fi
      [[ $path != $rest && -n $host && -n $path ]] && print -r -- "https://$host/$path"
      return
    fi

    if [[ $url == *@*:* ]]; then
      rest=${url#*@}
      host=${rest%%:*}
      path=${rest#*:}
      [[ -n $host && -n $path ]] && print -r -- "https://$host/$path"
      return
    fi

    if [[ $url == *:* ]]; then
      host=${url%%:*}
      path=${url#*:}
      [[ -n $host && -n $path ]] && print -r -- "https://$host/$path"
      return
    fi
  }

  __cailoxo_git_url_start() {
    (( __CAILOXO_GIT_URL )) || return
    [[ -n $upstream_url ]] || return
    __cailoxo_pansi $'\e]8;;'"$upstream_url"$'\e\\'
  }

  __cailoxo_git_url_end() {
    (( __CAILOXO_GIT_URL )) || return
    [[ -n $upstream_url ]] || return
    __cailoxo_pansi $'\e]8;;\e\\'
  }

  __cailoxo_upstream_icon() {
    (( __CAILOXO_FETCH_UPSTREAM_ICON )) || return
    local remote url provider upstream_icon=
    remote=$(__cailoxo_remote_name)
    url=$(git config --get "remote.$remote.url" 2>/dev/null) || return
    provider=$(__cailoxo_upstream_provider "$url")
    case $provider in
      azure_devops) upstream_icon='󰿕 ' ;;
      bitbucket) upstream_icon=' ' ;;
      codeberg) upstream_icon=' ' ;;
      gitea) upstream_icon='' ;;
      github) upstream_icon=' ' ;;
      gitlab) upstream_icon=' ' ;;
    esac
    print -r -- "$upstream_icon"
  }

  __cailoxo_remote_name() {
    local remote
    remote=$(git config --get "branch.$branch.remote" 2>/dev/null) || remote=origin
    [[ -n $remote ]] || remote=origin
    print -r -- "$remote"
  }

  __cailoxo_now_s() {
    zmodload zsh/datetime 2>/dev/null
    print -r -- "${EPOCHSECONDS:-$(date +%s 2>/dev/null || print -r -- 0)}"
  }

  __cailoxo_start_fetch() {
    (( __CAILOXO_FETCH_REMOTE )) || return
    [[ -n $branch ]] || return
    [[ -n $__CAILOXO_FETCH_FD ]] && return

    local remote root key now upstream_ref before fd
    remote=$(__cailoxo_remote_name)
    root=$(git rev-parse --show-toplevel 2>/dev/null) || return
    [[ -n $root && -n $remote ]] || return
    key="$root|$remote"
    now=$(__cailoxo_now_s)
    if [[ $__CAILOXO_FETCH_LAST_KEY == "$key" && $(( now - __CAILOXO_FETCH_LAST_START_S )) -lt $__CAILOXO_FETCH_REMOTE_INTERVAL_S ]]; then
      return
    fi

    upstream_ref=$(git rev-parse --symbolic-full-name "${branch}@{upstream}" 2>/dev/null) || upstream_ref=
    [[ -n $upstream_ref ]] || return
    before=$(git rev-parse --verify "$upstream_ref" 2>/dev/null) || before=
    zmodload zsh/system 2>/dev/null || return
    __CAILOXO_FETCH_LAST_KEY=$key
    __CAILOXO_FETCH_LAST_START_S=$now
    sysopen -r -o cloexec -u fd <(
      cd "$root" || exit 0
      if (( __CAILOXO_FETCH_REMOTE_TIMEOUT_S > 0 )) && command -v timeout >/dev/null 2>&1; then
        command timeout "${__CAILOXO_FETCH_REMOTE_TIMEOUT_S}s" git fetch --quiet --no-tags "$remote" >/dev/null 2>&1
      else
        command git fetch --quiet --no-tags "$remote" >/dev/null 2>&1
      fi
      local after
      after=$(git rev-parse --verify "$upstream_ref" 2>/dev/null) || after=
      [[ -n $after && $before != $after ]] && print -rn -- changed
    ) || return
    __CAILOXO_FETCH_FD=$fd
    zle -F $fd __cailoxo_fetch_done 2>/dev/null || {
      exec {fd}>&-
      __CAILOXO_FETCH_FD=
    }
  }

  __cailoxo_fetch_done() {
    local fd=$1 buf=
    [[ -n $fd ]] || fd=$__CAILOXO_FETCH_FD
    [[ -n $fd ]] || return
    zle -F $fd 2>/dev/null || true
    sysread -i $fd 'buf[$#buf+1]' 2>/dev/null || true
    exec {fd}>&- 2>/dev/null || true
    __CAILOXO_FETCH_FD=
    [[ $buf == *changed* ]] && __cailoxo_winch
  }

  __cailoxo_apply_template() {
    local tpl=$1
    local before rest body after then_part else_part
    while [[ $tpl == *'{{ if status }}'* ]]; do
      before=${tpl%%'{{ if status }}'*}
      rest=${tpl#*'{{ if status }}'}
      body=${rest%%'{{ end }}'*}
      after=${rest#*'{{ end }}'}
      if [[ $body == *'{{ else }}'* ]]; then
        then_part=${body%%'{{ else }}'*}
        else_part=${body#*'{{ else }}'}
      else
        then_part=$body
        else_part=
      fi
      if [[ -n $git_status ]]; then
        tpl="${before}${then_part}${after}"
      else
        tpl="${before}${else_part}${after}"
      fi
    done
    tpl=${tpl//\{\{ icon \}\}/${os_icon}}
    tpl=${tpl//\{\{icon\}\}/${os_icon}}
    tpl=${tpl//\{\{ path \}\}/${render_path}}
    tpl=${tpl//\{\{path\}\}/${render_path}}
    tpl=${tpl//\{\{ status \}\}/${git_status}}
    tpl=${tpl//\{\{status\}\}/${git_status}}
    tpl=${tpl//\{\{ branch_icon \}\}/${branch_icon}}
    tpl=${tpl//\{\{branch_icon\}\}/${branch_icon}}
    tpl=${tpl//\{\{ upstream_icon \}\}/${upstream_icon}}
    tpl=${tpl//\{\{upstream_icon\}\}/${upstream_icon}}
    tpl=${tpl//\{\{ branch \}\}/${branch}}
    tpl=${tpl//\{\{branch\}\}/${branch}}

    print -r -- $tpl
  }

  __cailoxo_path_template() {
    local tpl=$__CAILOXO_PATH_TEMPLATE
    local before=${tpl%%'{{ if home }}'*}
    local rest=${tpl#*'{{ if home }}'}
    if [[ $rest == $tpl ]]; then
      __cailoxo_apply_template "$tpl"
      return
    fi
    local home_part=${rest%%'{{ else }}'*}
    rest=${rest#*'{{ else }}'}
    local other_part=${rest%%'{{ end }}'*}
    local after=${rest#*'{{ end }}'}
    if [[ $is_home == 1 ]]; then
      __cailoxo_apply_template "${before}${home_part}${after}"
    else
      __cailoxo_apply_template "${before}${other_part}${after}"
    fi
  }

  __cailoxo_shorten_path() {
    local budget=$1
    local display
    if [[ $PWD == $HOME ]]; then
      display='~'
    elif [[ $PWD == $HOME/* ]]; then
      display="~${PWD#$HOME}"
    else
      display=$PWD
    fi

    if (( ${#display} <= budget )); then
      print -r -- $display
      return
    fi

    local prefix rest
    if [[ $display == ~/* ]]; then
      prefix='~'
      rest=${display#\~/}
    elif [[ $display == /* ]]; then
      prefix=''
      rest=${display#/}
    else
      prefix=''
      rest=$display
    fi

    local -a parts
    parts=(${(s:/:)rest})
    local count=${#parts}
    if (( count == 0 )); then
      print -r -- $display
      return
    fi

    local current=$parts[-1]
    if (( budget <= 4 )); then
      print -r -- "…/$current"
      return
    fi

    local candidate
    if (( count >= 2 )); then
      candidate="${prefix:+$prefix/}…/$parts[-2]/$current"
      if (( ${#candidate} <= budget )); then
        print -r -- $candidate
        return
      fi
    fi

    candidate="${prefix:+$prefix/}…/$current"
    if (( ${#candidate} <= budget )); then
      print -r -- $candidate
      return
    fi

    print -r -- "…/$current"
  }

  __cailoxo_status_item() {
    local name=$1 template count
    case $name in
    behind) template='⇣{{ count }}' ; count=${behind} ;;
    ahead) template='⇡{{ count }}' ; count=${ahead} ;;
    stashed) template='#{{ count }}' ; count=${stashed} ;;
    action) template='{{ action }}' ; count=${action} ;;
    conflicted) template='={{ count }}' ; count=${conflicted} ;;
    staged) template='+{{ count }}' ; count=${staged} ;;
    modified) template='!{{ count }}' ; count=${modified} ;;
    untracked) template='?{{ count }}' ; count=${untracked} ;;
    renamed) template='»{{ count }}' ; count=${renamed} ;;
    deleted) template='✘{{ count }}' ; count=${deleted} ;;
    esac
    if [[ $name == action ]]; then
      [[ -n $action ]] || return
      print -r -- ${template//\{\{ action \}\}/$action}
      return
    fi
    (( count > 0 )) || return
    print -r -- ${template//\{\{ count \}\}/$count}
  }

  __cailoxo_git_file() {
    git rev-parse --git-path "$1" 2>/dev/null
  }

  __cailoxo_git_action_with_progress() {
    local action=$1 dir=$2 next= last=
    [[ -r $dir/msgnum ]] && next=$(<$dir/msgnum)
    [[ -r $dir/end ]] && last=$(<$dir/end)
    [[ -r $dir/next ]] && next=$(<$dir/next)
    [[ -r $dir/last ]] && last=$(<$dir/last)
    if [[ -n $next && -n $last ]]; then
      print -r -- "$action $next/$last"
    else
      print -r -- "$action"
    fi
  }

  __cailoxo_git_action() {
    local path
    path=$(__cailoxo_git_file rebase-merge)
    if [[ -d $path ]]; then
      if [[ -e $path/interactive ]]; then
        __cailoxo_git_action_with_progress rebase-i "$path"
      else
        __cailoxo_git_action_with_progress rebase-m "$path"
      fi
      return
    fi

    path=$(__cailoxo_git_file rebase-apply)
    if [[ -d $path ]]; then
      if [[ -e $path/rebasing ]]; then
        __cailoxo_git_action_with_progress rebase "$path"
      elif [[ -e $path/applying ]]; then
        __cailoxo_git_action_with_progress am "$path"
      else
        __cailoxo_git_action_with_progress am/rebase "$path"
      fi
      return
    fi

    path=$(__cailoxo_git_file MERGE_HEAD)
    [[ -e $path ]] && { print -r -- merge; return; }
    path=$(__cailoxo_git_file REVERT_HEAD)
    if [[ -e $path ]]; then
      path=$(__cailoxo_git_file sequencer)
      [[ -d $path ]] && print -r -- revert-seq || print -r -- revert
      return
    fi
    path=$(__cailoxo_git_file CHERRY_PICK_HEAD)
    if [[ -e $path ]]; then
      path=$(__cailoxo_git_file sequencer)
      [[ -d $path ]] && print -r -- cherry-seq || print -r -- cherry
      return
    fi
    path=$(__cailoxo_git_file BISECT_LOG)
    [[ -e $path ]] && print -r -- bisect
  }

  __cailoxo_git_info() {
    branch=
    git_status=
    git_dirty=0
    upstream=
    upstream_icon=
    upstream_url=
    local inside
    inside=$(git rev-parse --is-inside-work-tree 2>/dev/null) || return
    [[ $inside == true ]] || return

    branch=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null) || branch=
    [[ -n $branch ]] || return
    if (( __CAILOXO_FETCH_UPSTREAM_ICON || __CAILOXO_GIT_URL )); then
      local remote
      remote=$(__cailoxo_remote_name)
      upstream_url=$(git config --get "remote.$remote.url" 2>/dev/null) || upstream_url=
      upstream=$(__cailoxo_upstream_provider "$upstream_url")
      if (( __CAILOXO_FETCH_UPSTREAM_ICON )); then
        upstream_icon=$(__cailoxo_upstream_icon)
      fi
      upstream_url=$(__cailoxo_clean_git_url "$upstream_url")
    fi
    __cailoxo_start_fetch
    (( __CAILOXO_GIT_STATUS )) || return

    local ahead=0 behind=0 action= conflicted=0 untracked=0 modified=0 staged=0 renamed=0 deleted=0 stashed=0
    local out line code x y
    out=$(git status --porcelain=v1 2>/dev/null)
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      code=${line[1,2]}
      if [[ $code == '??' ]]; then
        (( untracked++ ))
        continue
      fi
      case $code in
        DD|AU|UD|UA|DU|AA|UU) (( conflicted++ )); continue ;;
      esac
      x=${line[1,1]}
      y=${line[2,2]}
      [[ $x == R ]] && (( renamed++ ))
      [[ $x == D || $y == D ]] && (( deleted++ ))
      [[ $x != ' ' && $x != R && $x != D ]] && (( staged++ ))
      [[ $y != ' ' && $y != D ]] && (( modified++ ))
    done <<< $out

    ahead=$(git rev-list --count '@{upstream}..HEAD' 2>/dev/null || print -r -- 0)
    behind=$(git rev-list --count 'HEAD..@{upstream}' 2>/dev/null || print -r -- 0)
    action=$(__cailoxo_git_action)
    stashed=$(git stash list 2>/dev/null | wc -l | tr -d ' ')
    (( conflicted || untracked || modified || staged || renamed || deleted )) && git_dirty=1

    local -a items
    local item name
    for name in behind ahead stashed action conflicted staged modified untracked renamed deleted; do
      item=$(__cailoxo_status_item $name)
      [[ -n $item ]] && items+=("$item")
    done
    git_status=
    for item in "${items[@]}"; do
      if [[ -z $git_status ]]; then
        git_status=$item
      else
        git_status+="${__CAILOXO_STATUS_SEPARATOR}$item"
      fi
    done
  }

  __cailoxo_render_full_prompt() {
    local last_status=${1:-$?}
    local os_icon render_path home_icon folder_icon is_home branch branch_icon upstream upstream_icon upstream_url git_status git_dirty git_root_name
    os_icon=$(__cailoxo_os_icon)
    home_icon=$__CAILOXO_HOME_ICON
    folder_icon=$__CAILOXO_FOLDER_ICON
    branch_icon=$__CAILOXO_BRANCH_ICON
    [[ $PWD == $HOME ]] && is_home=1 || is_home=0
    __cailoxo_git_info
    git_root_name=$(__cailoxo_git_root_name)

    local git_text path_text os_text git_plain os_plain fixed budget git_style path_sep git_sep
    git_text=$(__cailoxo_apply_template "$__CAILOXO_GIT_TEMPLATE")
    if [[ -z $branch ]]; then
      git_text=
    fi

    os_text=$(__cailoxo_apply_template "$__CAILOXO_OS_TEMPLATE")
    # Budget applies only to {{ path }}. Account for icons, spaces and edge glyphs.
    local columns=${COLUMNS:-80}
    (( columns > 0 )) || columns=80
    os_plain=$(__cailoxo_plain_template "$os_text")
    git_plain=$(__cailoxo_plain_template "$git_text")
    fixed=$(( ${#os_plain} + ${#git_plain} + ${#__CAILOXO_HOME_ICON} + ${#__CAILOXO_FOLDER_ICON} + 10 ))
    budget=$(( columns - fixed ))
    (( budget < 1 )) && budget=1
    render_path=$(__cailoxo_format_path "$(__cailoxo_shorten_path $budget)" "$git_root_name")
    path_text=$(__cailoxo_path_template)

    if [[ -z $git_text ]]; then
      path_sep=$__CAILOXO_PATH_SEP_LAST
      git_sep=
    elif (( git_dirty )); then
      git_style=$__CAILOXO_GIT_DIRTY_STYLE
      path_sep=$__CAILOXO_PATH_SEP_DIRTY
      git_sep=$__CAILOXO_GIT_SEP_DIRTY
    else
      git_style=$__CAILOXO_GIT_CLEAN_STYLE
      path_sep=$__CAILOXO_PATH_SEP_CLEAN
      git_sep=$__CAILOXO_GIT_SEP_CLEAN
    fi

    local first second prompt_style
    first="$(__cailoxo_osc7)$(__cailoxo_pansi "$__CAILOXO_OS_STYLE")$(__cailoxo_style_template "$os_text")$(__cailoxo_pansi "$__CAILOXO_RESET")$__CAILOXO_OS_TAIL"
    first+="$(__cailoxo_pansi "$__CAILOXO_PATH_STYLE")$(__cailoxo_path_url_start)$(__cailoxo_style_template "$path_text")$(__cailoxo_path_url_end)$(__cailoxo_pansi "$__CAILOXO_RESET")$path_sep"
    if [[ -n $git_text ]]; then
      first+="$(__cailoxo_pansi "$git_style")$(__cailoxo_git_url_start)$(__cailoxo_style_template "$git_text")$(__cailoxo_git_url_end)$(__cailoxo_pansi "$__CAILOXO_RESET")$git_sep"
    fi

    if (( last_status == 0 )); then
      prompt_style=$__CAILOXO_PROMPT_OK_STYLE
    else
      prompt_style=$__CAILOXO_PROMPT_ERROR_STYLE
    fi
    second="$(__cailoxo_pansi "$prompt_style")$(__cailoxo_style_template "$__CAILOXO_PROMPT_TEMPLATE")$(__cailoxo_pansi "$__CAILOXO_RESET")"
    (( __CAILOXO_FINAL_SPACE )) && second+=' '
    print -r -- $first$'\n'$second
  }

  __cailoxo_render_transient_prompt() {
    local last_status=${1:-$?}
    local prompt_style
    if (( last_status == 0 )); then
      prompt_style=$__CAILOXO_TRANSIENT_OK_STYLE
    else
      prompt_style=$__CAILOXO_TRANSIENT_ERROR_STYLE
    fi
    print -r -- "$(__cailoxo_pansi "$prompt_style")$(__cailoxo_style_template "$__CAILOXO_TRANSIENT_TEMPLATE")$(__cailoxo_pansi "$__CAILOXO_RESET")"
  }

  __cailoxo_precmd() {
    typeset -g __CAILOXO_LAST_STATUS=$?
    setopt prompt_subst
    PROMPT='$(__cailoxo_render_full_prompt $__CAILOXO_LAST_STATUS)'
    RPROMPT=
  }

  __cailoxo_winch() {
    zle 2>/dev/null || return
    zle .reset-prompt 2>/dev/null || return
    zle -R 2>/dev/null || true
  }

  __cailoxo_zle_line_finish() {
    setopt prompt_subst
    PROMPT='$(__cailoxo_render_transient_prompt $__CAILOXO_LAST_STATUS)'
    RPROMPT=
    zle .reset-prompt
  }

  zle -N zle-line-finish __cailoxo_zle_line_finish
  add-zsh-hook precmd __cailoxo_precmd
  TRAPWINCH() { __cailoxo_winch }
  __cailoxo_precmd
fi
