# Generated by cailoxo. Do not edit by hand.
# shell: zsh

if [[ -o interactive ]]; then
  autoload -Uz add-zsh-hook

  typeset -g __CAILOXO_OS_TEMPLATE=' {{ icon }} '
  typeset -g __CAILOXO_PATH_TEMPLATE=' {{ if home }} {{ else }} {{ end }}{{ path }} '
  typeset -g __CAILOXO_GIT_TEMPLATE=' {{ upstream_icon }}{{ branch_icon }}{{ branch }}{{ if status }} {{ status }}{{ end }} '
  typeset -g __CAILOXO_PROMPT_TEMPLATE='   '
  typeset -g __CAILOXO_TRANSIENT_TEMPLATE=' '
  typeset -g __CAILOXO_HOME_ICON='~'
  typeset -g __CAILOXO_FOLDER_ICON='…'
  typeset -g __CAILOXO_EDGE_FORMAT='<b>%s</b>'
  typeset -g __CAILOXO_GITDIR_FORMAT='<b><i>%s</i></b>'
  typeset -g __CAILOXO_BRANCH_ICON=' '
  typeset -g __CAILOXO_STATUS_SEPARATOR=' '
  typeset -gi __CAILOXO_FETCH_UPSTREAM_ICON=1
  typeset -gi __CAILOXO_FETCH_REMOTE=1
  typeset -gi __CAILOXO_FETCH_REMOTE_INTERVAL_S=60
  typeset -gi __CAILOXO_FETCH_REMOTE_TIMEOUT_S=5
  typeset -gi __CAILOXO_MIN_DIRS=1
  typeset -gi __CAILOXO_FINAL_SPACE=1
  typeset -g __CAILOXO_OS_STYLE=$'\e[38;5;0m\e[48;5;7m'
  typeset -g __CAILOXO_PATH_STYLE=$'\e[38;5;0m\e[48;5;4m'
  typeset -g __CAILOXO_GIT_CLEAN_STYLE=$'\e[38;5;0m\e[48;5;2m'
  typeset -g __CAILOXO_GIT_DIRTY_STYLE=$'\e[38;5;0m\e[48;5;3m'
  typeset -g __CAILOXO_RESET=$'\e[0m'
  typeset -g __CAILOXO_OS_TAIL=$'%{\e[38;5;7m\e[48;5;4m%}%{\e[0m%}'
  typeset -g __CAILOXO_PATH_SEP_CLEAN=$'%{\e[38;5;4m\e[48;5;2m%}%{\e[0m%}'
  typeset -g __CAILOXO_PATH_SEP_DIRTY=$'%{\e[38;5;4m\e[48;5;3m%}%{\e[0m%}'
  typeset -g __CAILOXO_PATH_SEP_LAST=$'%{\e[38;5;4m%}%{\e[0m%}'
  typeset -g __CAILOXO_GIT_SEP_CLEAN=$'%{\e[38;5;2m%}%{\e[0m%}'
  typeset -g __CAILOXO_GIT_SEP_DIRTY=$'%{\e[38;5;3m%}%{\e[0m%}'
  typeset -g __CAILOXO_PROMPT_OK_STYLE=$'\e[38;5;2m'
  typeset -g __CAILOXO_PROMPT_ERROR_STYLE=$'\e[38;5;1m'
  typeset -g __CAILOXO_TRANSIENT_OK_STYLE=$'\e[38;5;2m'
  typeset -g __CAILOXO_TRANSIENT_ERROR_STYLE=$'\e[38;5;1m'

  __cailoxo_pansi() {
    print -nr -- "%{${1}%}"
  }

  __cailoxo_style_template() {
    local text=$1
    local bold_on bold_off underline_on underline_off overline_on overline_off italic_on italic_off
    local strike_on strike_off dim_on dim_off blink_on blink_off reverse_on reverse_off
    bold_on=$(__cailoxo_pansi $'\e[1m')
    bold_off=$(__cailoxo_pansi $'\e[22m')
    underline_on=$(__cailoxo_pansi $'\e[4m')
    underline_off=$(__cailoxo_pansi $'\e[24m')
    overline_on=$(__cailoxo_pansi $'\e[53m')
    overline_off=$(__cailoxo_pansi $'\e[55m')
    italic_on=$(__cailoxo_pansi $'\e[3m')
    italic_off=$(__cailoxo_pansi $'\e[23m')
    strike_on=$(__cailoxo_pansi $'\e[9m')
    strike_off=$(__cailoxo_pansi $'\e[29m')
    dim_on=$(__cailoxo_pansi $'\e[2m')
    dim_off=$(__cailoxo_pansi $'\e[22m')
    blink_on=$(__cailoxo_pansi $'\e[5m')
    blink_off=$(__cailoxo_pansi $'\e[25m')
    reverse_on=$(__cailoxo_pansi $'\e[7m')
    reverse_off=$(__cailoxo_pansi $'\e[27m')
    text=${text//'<b>'/$bold_on}
    text=${text//'<\/b>'/$bold_off}
    text=${text//'<u>'/$underline_on}
    text=${text//'<\/u>'/$underline_off}
    text=${text//'<o>'/$overline_on}
    text=${text//'<\/o>'/$overline_off}
    text=${text//'<i>'/$italic_on}
    text=${text//'<\/i>'/$italic_off}
    text=${text//'<s>'/$strike_on}
    text=${text//'<\/s>'/$strike_off}
    text=${text//'<d>'/$dim_on}
    text=${text//'<\/d>'/$dim_off}
    text=${text//'<f>'/$blink_on}
    text=${text//'<\/f>'/$blink_off}
    text=${text//'<r>'/$reverse_on}
    text=${text//'<\/r>'/$reverse_off}
    print -r -- "$text"
  }

  __cailoxo_plain_template() {
    local text=$1
    text=${text//'<b>'/}
    text=${text//'<\/b>'/}
    text=${text//'<u>'/}
    text=${text//'<\/u>'/}
    text=${text//'<o>'/}
    text=${text//'<\/o>'/}
    text=${text//'<i>'/}
    text=${text//'<\/i>'/}
    text=${text//'<s>'/}
    text=${text//'<\/s>'/}
    text=${text//'<d>'/}
    text=${text//'<\/d>'/}
    text=${text//'<f>'/}
    text=${text//'<\/f>'/}
    text=${text//'<r>'/}
    text=${text//'<\/r>'/}
    print -r -- "$text"
  }

  __cailoxo_format_part() {
    local value=$1 format=$2
    [[ -n $format ]] || { print -r -- "$value"; return }
    [[ $format == *%s* ]] || { print -r -- "$value"; return }
    print -r -- "${format//\%s/$value}"
  }

  __cailoxo_git_root_name() {
    local root
    root=$(git rev-parse --show-toplevel 2>/dev/null) || return
    print -r -- "${root:t}"
  }

  __cailoxo_format_path() {
    local input=$1 git_root=$2 prefix= rest absolute=0
    if [[ $input == '~' ]]; then
      __cailoxo_format_part "$input" "$__CAILOXO_EDGE_FORMAT"
      return
    elif [[ $input == '~/'* ]]; then
      prefix='~'
      rest=${input#\~/}
    elif [[ $input == '…/'* ]]; then
      prefix='…'
      rest=${input#…/}
    elif [[ $input == /* ]]; then
      absolute=1
      rest=${input#/}
    else
      rest=$input
    fi

    local -a raw_parts parts out
    raw_parts=("${(@s:/:)rest}")
    local part
    for part in "${raw_parts[@]}"; do
      [[ -n $part ]] && parts+=("$part")
    done

    if (( absolute )) && (( ${#parts} == 0 )); then
      __cailoxo_format_part / "$__CAILOXO_EDGE_FORMAT"
      return
    fi

    if [[ -n $prefix ]]; then
      if [[ $prefix == '…' ]]; then
        out+=("$prefix")
      else
        out+=("$(__cailoxo_format_part "$prefix" "$__CAILOXO_EDGE_FORMAT")")
      fi
    fi

    local i raw
    for (( i = 1; i <= ${#parts}; i++ )); do
      raw=$parts[$i]
      part=$raw
      if [[ -n $git_root && $raw == $git_root ]]; then
        part=$(__cailoxo_format_part "$part" "$__CAILOXO_GITDIR_FORMAT")
      fi
      if (( i == ${#parts} || (i == 1 && ${#out} == 0) )); then
        part=$(__cailoxo_format_part "$part" "$__CAILOXO_EDGE_FORMAT")
      fi
      out+=("$part")
    done

    local joined=${(j:/:)out}
    (( absolute )) && joined="/$joined"
    print -r -- "$joined"
  }

  __cailoxo_os_icon() {
    local id=unknown
    if [[ -r /etc/os-release ]]; then
      local line
      while IFS='=' read -r key value; do
        [[ $key == ID ]] || continue
        id=${value//\"/}
        break
      done < /etc/os-release
    elif [[ $OSTYPE == darwin* ]]; then
      id=macos
    elif [[ $OSTYPE == msys* || $OSTYPE == cygwin* ]]; then
      id=windows
    fi

    case ${id:l} in
      alpine) print -r -- '' ;;
      android) print -r -- '' ;;
      arch) print -r -- '' ;;
      centos) print -r -- '' ;;
      debian) print -r -- '' ;;
      fedora) print -r -- '' ;;
      freebsd) print -r -- '' ;;
      gentoo) print -r -- '' ;;
      linux) print -r -- '' ;;
      linux_mint) print -r -- '󰣭' ;;
      macos) print -r -- '' ;;
      manjaro) print -r -- '' ;;
      nixos) print -r -- '' ;;
      opensuse) print -r -- '' ;;
      raspbian) print -r -- '' ;;
      redhat) print -r -- '󱄛' ;;
      ubuntu) print -r -- '' ;;
      unknown) print -r -- '' ;;
      windows) print -r -- '' ;;
      wsl) print -r -- '' ;;
      *) print -r -- '' ;;
    esac
  }

  __cailoxo_upstream_provider() {
    local url=${1:l}
    if [[ $url == *github.com* ]]; then print -r -- github
    elif [[ $url == *gitlab.com* ]]; then print -r -- gitlab
    elif [[ $url == *bitbucket.org* ]]; then print -r -- bitbucket
    elif [[ $url == *codeberg.org* ]]; then print -r -- codeberg
    elif [[ $url == *gitea* ]]; then print -r -- gitea
    elif [[ $url == *dev.azure.com* || $url == *visualstudio.com* ]]; then print -r -- azure_devops
    fi
  }

  __cailoxo_upstream_icon() {
    (( __CAILOXO_FETCH_UPSTREAM_ICON )) || return
    local remote url provider upstream_icon=
    remote=$(__cailoxo_remote_name)
    url=$(git config --get "remote.$remote.url" 2>/dev/null) || return
    provider=$(__cailoxo_upstream_provider "$url")
    case $provider in
      azure_devops) upstream_icon='󰿕 ' ;;
      bitbucket) upstream_icon=' ' ;;
      codeberg) upstream_icon=' ' ;;
      gitea) upstream_icon='' ;;
      github) upstream_icon=' ' ;;
      gitlab) upstream_icon=' ' ;;
    esac
    print -r -- "$upstream_icon"
  }

  __cailoxo_remote_name() {
    local remote
    remote=$(git config --get "branch.$branch.remote" 2>/dev/null) || remote=origin
    [[ -n $remote ]] || remote=origin
    print -r -- "$remote"
  }

  __cailoxo_now_s() {
    zmodload zsh/datetime 2>/dev/null
    print -r -- "${EPOCHSECONDS:-$(date +%s 2>/dev/null || print -r -- 0)}"
  }

  __cailoxo_start_fetch() {
    (( __CAILOXO_FETCH_REMOTE )) || return
    [[ -n $branch ]] || return
    if [[ -n $__CAILOXO_FETCH_PID && -n $__CAILOXO_FETCH_MARKER && ! -e $__CAILOXO_FETCH_MARKER ]]; then
      kill -0 $__CAILOXO_FETCH_PID 2>/dev/null && return
    fi

    local remote root key now marker
    remote=$(__cailoxo_remote_name)
    root=$(git rev-parse --show-toplevel 2>/dev/null) || return
    [[ -n $root && -n $remote ]] || return
    key="$root|$remote"
    now=$(__cailoxo_now_s)
    if [[ $__CAILOXO_FETCH_LAST_KEY == "$key" && $(( now - __CAILOXO_FETCH_LAST_START_S )) -lt $__CAILOXO_FETCH_REMOTE_INTERVAL_S ]]; then
      return
    fi

    marker="${TMPDIR:-/tmp}/cailoxo-fetch-${$}-${RANDOM}"
    rm -f -- "$marker" 2>/dev/null
    __CAILOXO_FETCH_LAST_KEY=$key
    __CAILOXO_FETCH_LAST_START_S=$now
    __CAILOXO_FETCH_MARKER=$marker
    (
      cd "$root" || exit 0
      if (( __CAILOXO_FETCH_REMOTE_TIMEOUT_S > 0 )) && command -v timeout >/dev/null 2>&1; then
        command timeout "${__CAILOXO_FETCH_REMOTE_TIMEOUT_S}s" git fetch --quiet --no-tags "$remote" >/dev/null 2>&1
      else
        command git fetch --quiet --no-tags "$remote" >/dev/null 2>&1
      fi
      : >| "$marker"
    ) >/dev/null 2>&1 &
    __CAILOXO_FETCH_PID=$!
  }

  __cailoxo_chld() {
    [[ -n $__CAILOXO_FETCH_PID && -n $__CAILOXO_FETCH_MARKER && -e $__CAILOXO_FETCH_MARKER ]] || return
    wait $__CAILOXO_FETCH_PID 2>/dev/null || true
    rm -f -- "$__CAILOXO_FETCH_MARKER" 2>/dev/null
    __CAILOXO_FETCH_PID=
    __CAILOXO_FETCH_MARKER=
    __cailoxo_winch
  }

  __cailoxo_apply_template() {
    local tpl=$1
    local before rest body after then_part else_part
    while [[ $tpl == *'{{ if status }}'* ]]; do
      before=${tpl%%'{{ if status }}'*}
      rest=${tpl#*'{{ if status }}'}
      body=${rest%%'{{ end }}'*}
      after=${rest#*'{{ end }}'}
      if [[ $body == *'{{ else }}'* ]]; then
        then_part=${body%%'{{ else }}'*}
        else_part=${body#*'{{ else }}'}
      else
        then_part=$body
        else_part=
      fi
      if [[ -n $git_status ]]; then
        tpl="${before}${then_part}${after}"
      else
        tpl="${before}${else_part}${after}"
      fi
    done
    tpl=${tpl//\{\{ icon \}\}/${os_icon}}
    tpl=${tpl//\{\{ path \}\}/${render_path}}
    tpl=${tpl//\{\{ home_icon \}\}/${home_icon}}
    tpl=${tpl//\{\{ folder_icon \}\}/${folder_icon}}
    tpl=${tpl//\{\{ status \}\}/${git_status}}
    tpl=${tpl//\{\{ branch_icon \}\}/${branch_icon}}
    tpl=${tpl//\{\{ upstream_icon \}\}/${upstream_icon}}
    tpl=${tpl//\{\{ upstream \}\}/${upstream}}
    tpl=${tpl//\{\{ upstream_url \}\}/${upstream_url}}
    tpl=${tpl//\{\{ branch \}\}/${branch}}
    print -r -- $tpl
  }

  __cailoxo_path_template() {
    local tpl=$__CAILOXO_PATH_TEMPLATE
    local before=${tpl%%'{{ if home }}'*}
    local rest=${tpl#*'{{ if home }}'}
    if [[ $rest == $tpl ]]; then
      __cailoxo_apply_template "$tpl"
      return
    fi
    local home_part=${rest%%'{{ else }}'*}
    rest=${rest#*'{{ else }}'}
    local other_part=${rest%%'{{ end }}'*}
    local after=${rest#*'{{ end }}'}
    if [[ $is_home == 1 ]]; then
      __cailoxo_apply_template "${before}${home_part}${after}"
    else
      __cailoxo_apply_template "${before}${other_part}${after}"
    fi
  }

  __cailoxo_shorten_path() {
    local budget=$1
    local display
    if [[ $PWD == $HOME ]]; then
      display='~'
    elif [[ $PWD == $HOME/* ]]; then
      display="~${PWD#$HOME}"
    else
      display=$PWD
    fi

    if (( ${#display} <= budget )); then
      print -r -- $display
      return
    fi

    local prefix rest
    if [[ $display == ~/* ]]; then
      prefix='~'
      rest=${display#\~/}
    elif [[ $display == /* ]]; then
      prefix=''
      rest=${display#/}
    else
      prefix=''
      rest=$display
    fi

    local -a parts
    parts=(${(s:/:)rest})
    local count=${#parts}
    if (( count == 0 )); then
      print -r -- $display
      return
    fi

    local current=$parts[-1]
    if (( budget <= 4 )); then
      print -r -- "…/$current"
      return
    fi

    local candidate
    if (( count >= 2 )); then
      candidate="${prefix:+$prefix/}…/$parts[-2]/$current"
      if (( ${#candidate} <= budget )); then
        print -r -- $candidate
        return
      fi
    fi

    candidate="${prefix:+$prefix/}…/$current"
    if (( ${#candidate} <= budget )); then
      print -r -- $candidate
      return
    fi

    print -r -- "…/$current"
  }

  __cailoxo_status_item() {
    local name=$1 template count
    case $name in
    ahead) template='⇡{{ count }}' ; count=${ahead} ;;
    behind) template='⇣{{ count }}' ; count=${behind} ;;
    conflicted) template='={{ count }}' ; count=${conflicted} ;;
    untracked) template='?{{ count }}' ; count=${untracked} ;;
    modified) template='!{{ count }}' ; count=${modified} ;;
    staged) template='+{{ count }}' ; count=${staged} ;;
    renamed) template='»{{ count }}' ; count=${renamed} ;;
    deleted) template='✘{{ count }}' ; count=${deleted} ;;
    stashed) template='#{{ count }}' ; count=${stashed} ;;
    esac
    (( count > 0 )) || return
    print -r -- ${template//\{\{ count \}\}/$count}
  }

  __cailoxo_git_info() {
    branch=
    git_status=
    git_dirty=0
    upstream=
    upstream_icon=
    upstream_url=
    local inside
    inside=$(git rev-parse --is-inside-work-tree 2>/dev/null) || return
    [[ $inside == true ]] || return

    branch=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null) || branch=
    [[ -n $branch ]] || return
    if (( __CAILOXO_FETCH_UPSTREAM_ICON )); then
      local remote
      remote=$(__cailoxo_remote_name)
      upstream_url=$(git config --get "remote.$remote.url" 2>/dev/null) || upstream_url=
      upstream=$(__cailoxo_upstream_provider "$upstream_url")
      upstream_icon=$(__cailoxo_upstream_icon)
    fi
    __cailoxo_start_fetch

    local ahead=0 behind=0 conflicted=0 untracked=0 modified=0 staged=0 renamed=0 deleted=0 stashed=0
    local out line code x y
    out=$(git status --porcelain=v1 2>/dev/null)
    while IFS= read -r line; do
      [[ -n $line ]] || continue
      code=${line[1,2]}
      if [[ $code == '??' ]]; then
        (( untracked++ ))
        continue
      fi
      case $code in
        DD|AU|UD|UA|DU|AA|UU) (( conflicted++ )); continue ;;
      esac
      x=${line[1,1]}
      y=${line[2,2]}
      [[ $x == R ]] && (( renamed++ ))
      [[ $x == D || $y == D ]] && (( deleted++ ))
      [[ $x != ' ' && $x != R && $x != D ]] && (( staged++ ))
      [[ $y != ' ' && $y != D ]] && (( modified++ ))
    done <<< $out

    ahead=$(git rev-list --count '@{upstream}..HEAD' 2>/dev/null || print -r -- 0)
    behind=$(git rev-list --count 'HEAD..@{upstream}' 2>/dev/null || print -r -- 0)
    stashed=$(git stash list 2>/dev/null | wc -l | tr -d ' ')

    local -a items
    local item name
    for name in ahead behind conflicted untracked modified staged renamed deleted stashed; do
      item=$(__cailoxo_status_item $name)
      [[ -n $item ]] && items+=("$item")
    done
    git_status=
    for item in "${items[@]}"; do
      if [[ -z $git_status ]]; then
        git_status=$item
      else
        git_status+="${__CAILOXO_STATUS_SEPARATOR}$item"
      fi
    done
    (( ${#items} > 0 )) && git_dirty=1
  }

  __cailoxo_render_full_prompt() {
    local last_status=${1:-$?}
    local os_icon render_path home_icon folder_icon is_home branch branch_icon upstream upstream_icon upstream_url git_status git_dirty git_root_name
    os_icon=$(__cailoxo_os_icon)
    home_icon=$__CAILOXO_HOME_ICON
    folder_icon=$__CAILOXO_FOLDER_ICON
    branch_icon=$__CAILOXO_BRANCH_ICON
    [[ $PWD == $HOME ]] && is_home=1 || is_home=0
    __cailoxo_git_info
    git_root_name=$(__cailoxo_git_root_name)

    local git_text path_text os_text git_plain os_plain fixed budget git_style path_sep git_sep
    git_text=$(__cailoxo_apply_template "$__CAILOXO_GIT_TEMPLATE")
    if [[ -z $branch ]]; then
      git_text=
    fi

    os_text=$(__cailoxo_apply_template "$__CAILOXO_OS_TEMPLATE")
    # Budget applies only to {{ path }}. Account for icons, spaces and edge glyphs.
    local columns=${COLUMNS:-80}
    (( columns > 0 )) || columns=80
    os_plain=$(__cailoxo_plain_template "$os_text")
    git_plain=$(__cailoxo_plain_template "$git_text")
    fixed=$(( ${#os_plain} + ${#git_plain} + ${#__CAILOXO_HOME_ICON} + ${#__CAILOXO_FOLDER_ICON} + 10 ))
    budget=$(( columns - fixed ))
    (( budget < 1 )) && budget=1
    render_path=$(__cailoxo_format_path "$(__cailoxo_shorten_path $budget)" "$git_root_name")
    path_text=$(__cailoxo_path_template)

    if [[ -z $git_text ]]; then
      path_sep=$__CAILOXO_PATH_SEP_LAST
      git_sep=
    elif (( git_dirty )); then
      git_style=$__CAILOXO_GIT_DIRTY_STYLE
      path_sep=$__CAILOXO_PATH_SEP_DIRTY
      git_sep=$__CAILOXO_GIT_SEP_DIRTY
    else
      git_style=$__CAILOXO_GIT_CLEAN_STYLE
      path_sep=$__CAILOXO_PATH_SEP_CLEAN
      git_sep=$__CAILOXO_GIT_SEP_CLEAN
    fi

    local first second prompt_style
    first="$(__cailoxo_pansi "$__CAILOXO_OS_STYLE")$(__cailoxo_style_template "$os_text")$(__cailoxo_pansi "$__CAILOXO_RESET")$__CAILOXO_OS_TAIL"
    first+="$(__cailoxo_pansi "$__CAILOXO_PATH_STYLE")$(__cailoxo_style_template "$path_text")$(__cailoxo_pansi "$__CAILOXO_RESET")$path_sep"
    if [[ -n $git_text ]]; then
      first+="$(__cailoxo_pansi "$git_style")$(__cailoxo_style_template "$git_text")$(__cailoxo_pansi "$__CAILOXO_RESET")$git_sep"
    fi

    if (( last_status == 0 )); then
      prompt_style=$__CAILOXO_PROMPT_OK_STYLE
    else
      prompt_style=$__CAILOXO_PROMPT_ERROR_STYLE
    fi
    second="$(__cailoxo_pansi "$prompt_style")$(__cailoxo_style_template "$__CAILOXO_PROMPT_TEMPLATE")$(__cailoxo_pansi "$__CAILOXO_RESET")"
    (( __CAILOXO_FINAL_SPACE )) && second+=' '
    print -r -- $first$'\n'$second
  }

  __cailoxo_render_transient_prompt() {
    local last_status=${1:-$?}
    local prompt_style
    if (( last_status == 0 )); then
      prompt_style=$__CAILOXO_TRANSIENT_OK_STYLE
    else
      prompt_style=$__CAILOXO_TRANSIENT_ERROR_STYLE
    fi
    print -r -- "$(__cailoxo_pansi "$prompt_style")$(__cailoxo_style_template "$__CAILOXO_TRANSIENT_TEMPLATE")$(__cailoxo_pansi "$__CAILOXO_RESET")"
  }

  __cailoxo_precmd() {
    typeset -g __CAILOXO_LAST_STATUS=$?
    setopt prompt_subst
    PROMPT='$(__cailoxo_render_full_prompt $__CAILOXO_LAST_STATUS)'
    RPROMPT=
  }

  __cailoxo_winch() {
    zle 2>/dev/null || return
    zle .reset-prompt 2>/dev/null || return
    zle -R 2>/dev/null || true
  }

  __cailoxo_zle_line_finish() {
    setopt prompt_subst
    PROMPT='$(__cailoxo_render_transient_prompt $__CAILOXO_LAST_STATUS)'
    RPROMPT=
    zle .reset-prompt
  }

  zle -N zle-line-finish __cailoxo_zle_line_finish
  add-zsh-hook precmd __cailoxo_precmd
  TRAPWINCH() { __cailoxo_winch }
  TRAPCHLD() { __cailoxo_chld }
  __cailoxo_precmd
fi
