[metadata]
name = "Bearded Theme Void"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c7bfdb"
background = "#15111e"
cursor_bg = "#585785"
cursor_border = "#585785"
cursor_fg = "#171322"
selection_bg = "#312855"
selection_fg = "#c7bfdb"
scrollbar_thumb = "#2b2736"
split = "#0a080e"
ansi = ["#171322", "#C13838", "#14b871", "#585785", "#04c4d9", "#A8547A", "#89C4FF", "#c7bfdb"]
brights = ["#43365f", "#e61313", "#00cc74", "#3836a6", "#00c7dd", "#ce2e76", "#89c4ff", "#ffffff"]

[colors.tab_bar]
background = "#120f1b"
inactive_tab_edge = "#120f1b"
inactive_tab_edge_hover = "#120f1b"

[colors.tab_bar.active_tab]
bg_color = "#171322"
fg_color = "#c7bfdb"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#120f1b"
fg_color = "#4f4273"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#171322"
fg_color = "#c7bfdb"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#120f1b"
fg_color = "#4f4273"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#171322"
fg_color = "#c7bfdb"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

