[metadata]
name = "Bearded Theme Feat Gold D Raynh Light"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#0f212d"
background = "#f0f0f0"
cursor_bg = "#d0a00f"
cursor_border = "#d0a00f"
cursor_fg = "#f5f5f5"
selection_bg = "#c0d4ed"
selection_fg = "#0f212d"
scrollbar_thumb = "#cbcdd0"
split = "#cfcfcf"
ansi = ["#f5f5f5", "#f7775a", "#03810d", "#d0a00f", "#037ed1", "#002e74", "#009c8f", "#0f212d"]
brights = ["#bdbdbd", "#ff7252", "#00840a", "#dfa800", "#007fd4", "#002e74", "#009c8f", "#295979"]

[colors.tab_bar]
background = "#ececec"
inactive_tab_edge = "#ececec"
inactive_tab_edge_hover = "#ececec"

[colors.tab_bar.active_tab]
bg_color = "#f5f5f5"
fg_color = "#0f212d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#ececec"
fg_color = "#7197b0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#f5f5f5"
fg_color = "#0f212d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#ececec"
fg_color = "#7197b0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#f5f5f5"
fg_color = "#0f212d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

