[metadata]
name = "Bearded Theme Stained Blue"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#bec6df"
background = "#101522"
cursor_bg = "#c9a022"
cursor_border = "#c9a022"
cursor_fg = "#121726"
selection_bg = "#20325d"
selection_fg = "#bec6df"
scrollbar_thumb = "#262b3a"
split = "#080a11"
ansi = ["#121726", "#C13838", "#37ae6f", "#c9a022", "#3398DB", "#CC71BC", "#24B5A8", "#bec6df"]
brights = ["#314067", "#e61313", "#15d06d", "#ebb100", "#0f9fff", "#e954cf", "#03d6c3", "#ffffff"]

[colors.tab_bar]
background = "#0e121e"
inactive_tab_edge = "#0e121e"
inactive_tab_edge_hover = "#0e121e"

[colors.tab_bar.active_tab]
bg_color = "#121726"
fg_color = "#bec6df"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#0e121e"
fg_color = "#3c4c7c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#121726"
fg_color = "#bec6df"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#0e121e"
fg_color = "#3c4c7c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#121726"
fg_color = "#bec6df"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

