[metadata]
name = "Bearded Theme Arc Blueberry"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#bcc1dc"
background = "#0f121e"
cursor_bg = "#EACD61"
cursor_border = "#EACD61"
cursor_fg = "#111422"
selection_bg = "#313c53"
selection_fg = "#bcc1dc"
scrollbar_thumb = "#252836"
split = "#07080e"
ansi = ["#111422", "#E35535", "#3CEC85", "#EACD61", "#69C3FF", "#F38CEC", "#22ECDB", "#bcc1dc"]
brights = ["#313b62", "#ff4319", "#29ff82", "#ffd94c", "#69c3ff", "#ff80f6", "#0fffeb", "#ffffff"]

[colors.tab_bar]
background = "#0d101b"
inactive_tab_edge = "#0d101b"
inactive_tab_edge_hover = "#0d101b"

[colors.tab_bar.active_tab]
bg_color = "#111422"
fg_color = "#bcc1dc"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#0d101b"
fg_color = "#3c4776"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#111422"
fg_color = "#bcc1dc"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#0d101b"
fg_color = "#3c4776"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#111422"
fg_color = "#bcc1dc"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

