[metadata]
name = "Bearded Theme Black Emerald Soft"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c9d4d8"
background = "#141f22"
cursor_bg = "#c7910c"
cursor_border = "#c7910c"
cursor_fg = "#162226"
selection_bg = "#214445"
selection_fg = "#c9d4d8"
scrollbar_thumb = "#1b3133"
split = "#0b1113"
ansi = ["#162226", "#E35535", "#00a884", "#c7910c", "#11B7D4", "#d46ec0", "#38c7bd", "#c9d4d8"]
brights = ["#11B7D4", "#E35535", "#00a884", "#c7910c", "#11B7D4", "#d46ec0", "#38c7bd", "#c9d4d8"]

[colors.tab_bar]
background = "#121c1f"
inactive_tab_edge = "#121c1f"
inactive_tab_edge_hover = "#121c1f"

[colors.tab_bar.active_tab]
bg_color = "#162226"
fg_color = "#38c7bd"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#121c1f"
fg_color = "#8eb9c7"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#162226"
fg_color = "#38c7bd"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#121c1f"
fg_color = "#8eb9c7"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#162226"
fg_color = "#38c7bd"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

