[metadata]
name = "Bearded Theme Solarized Dark"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c3e0e9"
background = "#112830"
cursor_bg = "#e2ae10"
cursor_border = "#e2ae10"
cursor_fg = "#132c34"
selection_bg = "#215659"
selection_fg = "#c3e0e9"
scrollbar_thumb = "#294048"
split = "#0b191e"
ansi = ["#132c34", "#f45645", "#a5b82e", "#e2ae10", "#4db0f7", "#df96d9", "#26bbae", "#c3e0e9"]
brights = ["#2c677b", "#ff4d3a", "#bedb0c", "#f2b600", "#45b1ff", "#f481ea", "#04ddca", "#ffffff"]

[colors.tab_bar]
background = "#10252c"
inactive_tab_edge = "#10252c"
inactive_tab_edge_hover = "#10252c"

[colors.tab_bar.active_tab]
bg_color = "#132c34"
fg_color = "#c3e0e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#10252c"
fg_color = "#367b90"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#132c34"
fg_color = "#c3e0e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#10252c"
fg_color = "#367b90"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#132c34"
fg_color = "#c3e0e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

