[metadata]
name = "Bearded Theme Feat Webdevcody"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#81f0fe"
background = "#001315"
cursor_bg = "#f1d868"
cursor_border = "#f1d868"
cursor_fg = "#00171a"
selection_bg = "#10545e"
selection_fg = "#81f0fe"
scrollbar_thumb = "#152e32"
split = "#000000"
ansi = ["#00171a", "#e61e3f", "#60e66f", "#f1d868", "#f1d868", "#f75f94", "#f1d868", "#81f0fe"]
brights = ["#006f7b", "#ff052e", "#47ff5c", "#ffe15a", "#ffe15a", "#ff5792", "#ffe15a", "#e6fcff"]

[colors.tab_bar]
background = "#000d0f"
inactive_tab_edge = "#000d0f"
inactive_tab_edge_hover = "#000d0f"

[colors.tab_bar.active_tab]
bg_color = "#1c1f22"
fg_color = "#81f0fe"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#000d0f"
fg_color = "#018799"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1c1f22"
fg_color = "#81f0fe"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#000d0f"
fg_color = "#018799"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#1c1f22"
fg_color = "#81f0fe"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

