[metadata]
name = "Bearded Theme Classics Anthracite"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c8ccd4"
background = "#16181c"
cursor_bg = "#c9a022"
cursor_border = "#c9a022"
cursor_fg = "#181a1f"
selection_bg = "#3c4046"
selection_fg = "#c8ccd4"
scrollbar_thumb = "#2c2f33"
split = "#0b0c0e"
ansi = ["#181a1f", "#C13838", "#37ae6f", "#c9a022", "#3398DB", "#CC71BC", "#24B5A8", "#c8ccd4"]
brights = ["#434955", "#e61313", "#15d06d", "#ebb100", "#0f9fff", "#e954cf", "#03d6c3", "#ffffff"]

[colors.tab_bar]
background = "#131519"
inactive_tab_edge = "#131519"
inactive_tab_edge_hover = "#131519"

[colors.tab_bar.active_tab]
bg_color = "#181a1f"
fg_color = "#c8ccd4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#131519"
fg_color = "#515766"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#181a1f"
fg_color = "#c8ccd4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#131519"
fg_color = "#515766"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#181a1f"
fg_color = "#c8ccd4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

