[metadata]
name = "Bearded Theme Aquarelle Lilac"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#d9d9e3"
background = "#22212f"
cursor_bg = "#f3e1ac"
cursor_border = "#f3e1ac"
cursor_fg = "#252433"
selection_bg = "#423d67"
selection_fg = "#d9d9e3"
scrollbar_thumb = "#3a3947"
split = "#181721"
ansi = ["#252433", "#e87a70", "#aada77", "#f3e1ac", "#73bee9", "#edc1ea", "#a9edd9", "#d9d9e3"]
brights = ["#4d4b6b", "#ff6759", "#abf45d", "#ffe7a0", "#5dc4ff", "#f9b5f4", "#99fddf", "#ffffff"]

[colors.tab_bar]
background = "#201f2c"
inactive_tab_edge = "#201f2c"
inactive_tab_edge_hover = "#201f2c"

[colors.tab_bar.active_tab]
bg_color = "#252433"
fg_color = "#d9d9e3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#201f2c"
fg_color = "#5c5a7d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#252433"
fg_color = "#d9d9e3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#201f2c"
fg_color = "#5c5a7d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#252433"
fg_color = "#d9d9e3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

