[metadata]
name = "Bearded Theme Hc Brewing Storm"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c0dcf3"
background = "#0b273d"
cursor_bg = "#fff0a6"
cursor_border = "#fff0a6"
cursor_fg = "#0c2a42"
selection_bg = "#366169"
selection_fg = "#c0dcf3"
scrollbar_thumb = "#253e55"
split = "#071a28"
ansi = ["#0c2a42", "#ff5e4c", "#84ffad", "#fff0a6", "#3391e3", "#f1c6ee", "#22D3B1", "#c0dcf3"]
brights = ["#1b5e93", "#ff5e4c", "#84ffad", "#fff0a6", "#1793ff", "#fcbbf7", "#00f5c6", "#ffffff"]

[colors.tab_bar]
background = "#0a2439"
inactive_tab_edge = "#0a2439"
inactive_tab_edge_hover = "#0a2439"

[colors.tab_bar.active_tab]
bg_color = "#1b3c50"
fg_color = "#c0dcf3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#0a2439"
fg_color = "#216fad"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1b3c50"
fg_color = "#c0dcf3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#0a2439"
fg_color = "#216fad"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#1b3c50"
fg_color = "#c0dcf3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

