[metadata]
name = "Bearded Theme Feat Gold D Raynh"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#b8c4e4"
background = "#0e1424"
cursor_bg = "#ffd000"
cursor_border = "#ffd000"
cursor_fg = "#0f1628"
selection_bg = "#23325a"
selection_fg = "#b8c4e4"
scrollbar_thumb = "#242a3d"
split = "#070a12"
ansi = ["#0f1628", "#f7775a", "#21ff7d", "#ffd000", "#3eb2ff", "#e4ac73", "#44f8e9", "#b8c4e4"]
brights = ["#2b3d6d", "#ff7252", "#21ff7d", "#ffd000", "#3eb2ff", "#fdac5a", "#3dffef", "#ffffff"]

[colors.tab_bar]
background = "#0c1220"
inactive_tab_edge = "#0c1220"
inactive_tab_edge_hover = "#0c1220"

[colors.tab_bar.active_tab]
bg_color = "#0f1628"
fg_color = "#b8c4e4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#0c1220"
fg_color = "#334984"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#0f1628"
fg_color = "#b8c4e4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#0c1220"
fg_color = "#334984"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#0f1628"
fg_color = "#b8c4e4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

