[metadata]
name = "Bearded Theme Aquarelle Hydrangea"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#dadde9"
background = "#202438"
cursor_bg = "#f3e1ac"
cursor_border = "#f3e1ac"
cursor_fg = "#22273c"
selection_bg = "#34436b"
selection_fg = "#dadde9"
scrollbar_thumb = "#383c50"
split = "#171a28"
ansi = ["#22273c", "#e87a70", "#aada77", "#f3e1ac", "#73bee9", "#edc1ea", "#a9edd9", "#dadde9"]
brights = ["#454e79", "#ff6759", "#abf45d", "#ffe7a0", "#5dc4ff", "#f9b5f4", "#99fddf", "#ffffff"]

[colors.tab_bar]
background = "#1e2235"
inactive_tab_edge = "#1e2235"
inactive_tab_edge_hover = "#1e2235"

[colors.tab_bar.active_tab]
bg_color = "#22273c"
fg_color = "#dadde9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1e2235"
fg_color = "#515d8c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#22273c"
fg_color = "#dadde9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1e2235"
fg_color = "#515d8c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#22273c"
fg_color = "#dadde9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

