[metadata]
name = "Bearded Theme Hc Ebony"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c8c8d5"
background = "#16161d"
cursor_bg = "#F5DF76"
cursor_border = "#F5DF76"
cursor_fg = "#181820"
selection_bg = "#4a4b54"
selection_fg = "#c8c8d5"
scrollbar_thumb = "#2c2c34"
split = "#0b0b0f"
ansi = ["#181820", "#fd604f", "#AFEA7B", "#F5DF76", "#7fd7f5", "#e4a3df", "#22D3B1", "#c8c8d5"]
brights = ["#424257", "#ff5e4d", "#aeff66", "#ffe66c", "#75dcff", "#f691ee", "#00f5c6", "#ffffff"]

[colors.tab_bar]
background = "#13131a"
inactive_tab_edge = "#13131a"
inactive_tab_edge_hover = "#13131a"

[colors.tab_bar.active_tab]
bg_color = "#282831"
fg_color = "#c8c8d5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#13131a"
fg_color = "#505068"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#282831"
fg_color = "#c8c8d5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#13131a"
fg_color = "#505068"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#282831"
fg_color = "#c8c8d5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

