[metadata]
name = "Bearded Theme Milkshake Raspberry"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#15070b"
background = "#eee2e6"
cursor_bg = "#c08403"
cursor_border = "#c08403"
cursor_fg = "#f1e8eb"
selection_bg = "#edafb5"
selection_fg = "#15070b"
scrollbar_thumb = "#c9bdc1"
split = "#d4b8c2"
ansi = ["#f1e8eb", "#d12525", "#008b17", "#c08403", "#0076c5", "#c121a4", "#008f8f", "#15070b"]
brights = ["#c8a2af", "#f60000", "#008b17", "#c38500", "#0076c5", "#e200b9", "#008f8f", "#622133"]

[colors.tab_bar]
background = "#eadde1"
inactive_tab_edge = "#eadde1"
inactive_tab_edge_hover = "#eadde1"

[colors.tab_bar.active_tab]
bg_color = "#f1d6da"
fg_color = "#15070b"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#eadde1"
fg_color = "#a75b72"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#f1d6da"
fg_color = "#15070b"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#eadde1"
fg_color = "#a75b72"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#f1d6da"
fg_color = "#15070b"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

