[metadata]
name = "Bearded Theme Altica"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c2ced1"
background = "#0f1a1f"
cursor_bg = "#d6ac63"
cursor_border = "#d6ac63"
cursor_fg = "#0f1c21"
selection_bg = "#163844"
selection_fg = "#c2ced1"
scrollbar_thumb = "#263136"
split = "#0a1217"
ansi = ["#0f1c21", "#C13838", "#14b871", "#d6ac63", "#04c4d9", "#A8547A", "#0187a6", "#c2ced1"]
brights = ["#305464", "#e61313", "#00cc74", "#f4b445", "#00c7dd", "#ce2e76", "#0088a7", "#fcfdfd"]

[colors.tab_bar]
background = "#0e171c"
inactive_tab_edge = "#0e171c"
inactive_tab_edge_hover = "#0e171c"

[colors.tab_bar.active_tab]
bg_color = "#0f1c21"
fg_color = "#c2ced1"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#0e171c"
fg_color = "#45565c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#0f1c21"
fg_color = "#c2ced1"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#0e171c"
fg_color = "#45565c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#0f1c21"
fg_color = "#c2ced1"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

