[metadata]
name = "Bearded Theme Black Gold Soft"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#d2d2d2"
background = "#1f1c1a"
cursor_bg = "#c7910c"
cursor_border = "#c7910c"
cursor_fg = "#221f1d"
selection_bg = "#46361e"
selection_fg = "#d2d2d2"
scrollbar_thumb = "#32291c"
split = "#11100f"
ansi = ["#221f1d", "#E35535", "#00a884", "#c7910c", "#11B7D4", "#d46ec0", "#38c7bd", "#d2d2d2"]
brights = ["#11B7D4", "#E35535", "#00a884", "#c7910c", "#11B7D4", "#d46ec0", "#38c7bd", "#d2d2d2"]

[colors.tab_bar]
background = "#1c1918"
inactive_tab_edge = "#1c1918"
inactive_tab_edge_hover = "#1c1918"

[colors.tab_bar.active_tab]
bg_color = "#221f1d"
fg_color = "#c7910c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1c1918"
fg_color = "#b8a99f"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#221f1d"
fg_color = "#c7910c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1c1918"
fg_color = "#b8a99f"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#221f1d"
fg_color = "#c7910c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

