[metadata]
name = "Bearded Theme Oled"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#b3b3b3"
background = "#000000"
cursor_bg = "#E0CF77"
cursor_border = "#E0CF77"
cursor_fg = "#000000"
selection_bg = "#252c47"
selection_fg = "#b3b3b3"
scrollbar_thumb = "#1d1d1d"
split = "#262626"
ansi = ["#000000", "#E87474", "#5CD4C3", "#E0CF77", "#63BBE5", "#E48CC5", "#6AD3CD", "#b3b3b3"]
brights = ["#333333", "#ff5d5d", "#3df3d9", "#f9e05e", "#49c4ff", "#f977cb", "#4df0e7", "#e6e6e6"]

[colors.tab_bar]
background = "#000000"
inactive_tab_edge = "#000000"
inactive_tab_edge_hover = "#000000"

[colors.tab_bar.active_tab]
bg_color = "#000000"
fg_color = "#b3b3b3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#000000"
fg_color = "#515151"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#000000"
fg_color = "#b3b3b3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#000000"
fg_color = "#515151"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#000000"
fg_color = "#b3b3b3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

