[metadata]
name = "Bearded Theme Hc Midnightvoid"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c3d2de"
background = "#131c23"
cursor_bg = "#F5DF76"
cursor_border = "#F5DF76"
cursor_fg = "#151f27"
selection_bg = "#48545e"
selection_fg = "#c3d2de"
scrollbar_thumb = "#29333b"
split = "#0a0f13"
ansi = ["#151f27", "#fd604f", "#AFEA7B", "#F5DF76", "#7fd7f5", "#e4a3df", "#22D3B1", "#c3d2de"]
brights = ["#375165", "#ff5e4d", "#aeff66", "#ffe66c", "#75dcff", "#f691ee", "#00f5c6", "#ffffff"]

[colors.tab_bar]
background = "#111920"
inactive_tab_edge = "#111920"
inactive_tab_edge_hover = "#111920"

[colors.tab_bar.active_tab]
bg_color = "#253039"
fg_color = "#c3d2de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#111920"
fg_color = "#436179"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#253039"
fg_color = "#c3d2de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#111920"
fg_color = "#436179"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#253039"
fg_color = "#c3d2de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

