[metadata]
name = "Bearded Theme Vivid Light"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#181818"
background = "#efefef"
cursor_bg = "#d48700"
cursor_border = "#d48700"
cursor_fg = "#f4f4f4"
selection_bg = "#cccccc"
selection_fg = "#181818"
scrollbar_thumb = "#cbcbcb"
split = "#cecece"
ansi = ["#f4f4f4", "#D62C2C", "#42DD76", "#d48700", "#28A9FF", "#E66DFF", "#00b8a9", "#181818"]
brights = ["#bcbcbc", "#fc0606", "#21fe6b", "#d48700", "#28a9ff", "#e66dff", "#00b8a9", "#4b4b4b"]

[colors.tab_bar]
background = "#ebebeb"
inactive_tab_edge = "#ebebeb"
inactive_tab_edge_hover = "#ebebeb"

[colors.tab_bar.active_tab]
bg_color = "#f4f4f4"
fg_color = "#181818"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#ebebeb"
fg_color = "#8a8a8a"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#f4f4f4"
fg_color = "#181818"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#ebebeb"
fg_color = "#8a8a8a"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#f4f4f4"
fg_color = "#181818"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

