[metadata]
name = "Bearded Theme Oceanic"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#cddde6"
background = "#182830"
cursor_bg = "#f6cc73"
cursor_border = "#f6cc73"
cursor_fg = "#1a2b34"
selection_bg = "#3c544c"
selection_fg = "#cddde6"
scrollbar_thumb = "#303f48"
split = "#101a20"
ansi = ["#1a2b34", "#ee5d75", "#97c892", "#f6cc73", "#5fb2df", "#d194cd", "#59c6c8", "#cddde6"]
brights = ["#3a6174", "#ff4c6a", "#83e179", "#ffcf6a", "#42bbfc", "#e87de1", "#38e6e9", "#ffffff"]

[colors.tab_bar]
background = "#16252d"
inactive_tab_edge = "#16252d"
inactive_tab_edge_hover = "#16252d"

[colors.tab_bar.active_tab]
bg_color = "#1a2b34"
fg_color = "#cddde6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#16252d"
fg_color = "#467188"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1a2b34"
fg_color = "#cddde6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#16252d"
fg_color = "#467188"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#1a2b34"
fg_color = "#cddde6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

