[metadata]
name = "Bearded Theme Oceanic Reversed"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c3d6e0"
background = "#131f25"
cursor_bg = "#f6cc73"
cursor_border = "#f6cc73"
cursor_fg = "#111c22"
selection_bg = "#374d44"
selection_fg = "#c3d6e0"
scrollbar_thumb = "#29363d"
split = "#0b1115"
ansi = ["#111c22", "#ee5d75", "#97c892", "#f6cc73", "#5fb2df", "#d194cd", "#59c6c8", "#c3d6e0"]
brights = ["#365768", "#ff4c6a", "#83e179", "#ffcf6a", "#42bbfc", "#e87de1", "#38e6e9", "#ffffff"]

[colors.tab_bar]
background = "#152229"
inactive_tab_edge = "#152229"
inactive_tab_edge_hover = "#152229"

[colors.tab_bar.active_tab]
bg_color = "#111c22"
fg_color = "#c3d6e0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#152229"
fg_color = "#41687c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#111c22"
fg_color = "#c3d6e0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#152229"
fg_color = "#41687c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#111c22"
fg_color = "#c3d6e0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

