[metadata]
name = "Bearded Theme Earth"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#caa5a5"
background = "#1f1819"
cursor_bg = "#C48519"
cursor_border = "#C48519"
cursor_fg = "#221b1b"
selection_bg = "#502b37"
selection_fg = "#caa5a5"
scrollbar_thumb = "#352a2b"
split = "#110d0d"
ansi = ["#221b1b", "#C13838", "#14b871", "#C48519", "#04c4d9", "#A8547A", "#4EAAA4", "#caa5a5"]
brights = ["#584547", "#e61313", "#00cc74", "#dd8c00", "#00c7dd", "#ce2e76", "#29cfc4", "#f0e5e5"]

[colors.tab_bar]
background = "#1c1616"
inactive_tab_edge = "#1c1616"
inactive_tab_edge_hover = "#1c1616"

[colors.tab_bar.active_tab]
bg_color = "#221b1b"
fg_color = "#caa5a5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1c1616"
fg_color = "#503939"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#221b1b"
fg_color = "#caa5a5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1c1616"
fg_color = "#503939"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#221b1b"
fg_color = "#caa5a5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

