[metadata]
name = "Bearded Theme Black Ruby Soft"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#d8cfd3"
background = "#24181e"
cursor_bg = "#c7910c"
cursor_border = "#c7910c"
cursor_fg = "#281a21"
selection_bg = "#4a212a"
selection_fg = "#d8cfd3"
scrollbar_thumb = "#371d24"
split = "#150e12"
ansi = ["#281a21", "#E35535", "#00a884", "#c7910c", "#11B7D4", "#d46ec0", "#38c7bd", "#d8cfd3"]
brights = ["#11B7D4", "#E35535", "#00a884", "#c7910c", "#11B7D4", "#d46ec0", "#38c7bd", "#d8cfd3"]

[colors.tab_bar]
background = "#21161b"
inactive_tab_edge = "#21161b"
inactive_tab_edge_hover = "#21161b"

[colors.tab_bar.active_tab]
bg_color = "#281a21"
fg_color = "#c62f52"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#21161b"
fg_color = "#c496ad"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#281a21"
fg_color = "#c62f52"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#21161b"
fg_color = "#c496ad"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#281a21"
fg_color = "#c62f52"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

