[metadata]
name = "Bearded Theme Monokai Metallian"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#d0d3de"
background = "#1b1e27"
cursor_bg = "#ffd866"
cursor_border = "#ffd866"
cursor_fg = "#1e212b"
selection_bg = "#3d424e"
selection_fg = "#d0d3de"
scrollbar_thumb = "#32353f"
split = "#111319"
ansi = ["#1e212b", "#fc6a67", "#a9dc76", "#ffd866", "#78dce8", "#e991e3", "#78e8c6", "#d0d3de"]
brights = ["#454c63", "#ff6764", "#a9f65c", "#ffd866", "#61eeff", "#fd7df4", "#61ffcf", "#ffffff"]

[colors.tab_bar]
background = "#191c24"
inactive_tab_edge = "#191c24"
inactive_tab_edge_hover = "#191c24"

[colors.tab_bar.active_tab]
bg_color = "#1e212b"
fg_color = "#d0d3de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#191c24"
fg_color = "#535b75"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1e212b"
fg_color = "#d0d3de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#191c24"
fg_color = "#535b75"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#1e212b"
fg_color = "#d0d3de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

