[metadata]
name = "Bearded Theme Milkshake Mint"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#000000"
background = "#e7efe9"
cursor_bg = "#c08403"
cursor_border = "#c08403"
cursor_fg = "#edf3ee"
selection_bg = "#b3d6c7"
selection_fg = "#000000"
scrollbar_thumb = "#c1c7c2"
split = "#bfd4c3"
ansi = ["#edf3ee", "#d12525", "#008b17", "#c08403", "#0076c5", "#c121a4", "#008f8f", "#000000"]
brights = ["#aac6b1", "#f60000", "#008b17", "#c38500", "#0076c5", "#e200b9", "#008f8f", "#333333"]

[colors.tab_bar]
background = "#e2ece4"
inactive_tab_edge = "#e2ece4"
inactive_tab_edge_hover = "#e2ece4"

[colors.tab_bar.active_tab]
bg_color = "#dbeae2"
fg_color = "#000000"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#e2ece4"
fg_color = "#677873"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#dbeae2"
fg_color = "#000000"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#e2ece4"
fg_color = "#677873"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#dbeae2"
fg_color = "#000000"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

