[metadata]
name = "Bearded Theme Coffee Cream"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#36221d"
background = "#e6dfdc"
cursor_bg = "#ad8200"
cursor_border = "#ad8200"
cursor_fg = "#EAE4E1"
selection_bg = "#e5bcae"
selection_fg = "#36221d"
scrollbar_thumb = "#cac0bc"
split = "#cbbbb4"
ansi = ["#EAE4E1", "#FF3A3A", "#51A200", "#ad8200", "#009DB5", "#CE4985", "#009b74", "#36221d"]
brights = ["#bca9a1", "#ff3a3a", "#51a200", "#ad8200", "#009db5", "#f12682", "#009b74", "#784c41"]

[colors.tab_bar]
background = "#e3dbd7"
inactive_tab_edge = "#e3dbd7"
inactive_tab_edge_hover = "#e3dbd7"

[colors.tab_bar.active_tab]
bg_color = "#EAE4E1"
fg_color = "#36221d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#e3dbd7"
fg_color = "#a69692"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#EAE4E1"
fg_color = "#36221d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#e3dbd7"
fg_color = "#a69692"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#EAE4E1"
fg_color = "#36221d"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

