[metadata]
name = "Bearded Theme Hc Wonderland Wood"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#d3d2e6"
background = "#1d1b32"
cursor_bg = "#fbe7c3"
cursor_border = "#fbe7c3"
cursor_fg = "#1F1D36"
selection_bg = "#5a515b"
selection_fg = "#d3d2e6"
scrollbar_thumb = "#35324a"
split = "#141222"
ansi = ["#1F1D36", "#ff7e70", "#91d6a7", "#fbe7c3", "#92b4ff", "#de98ae", "#7ddcbf", "#d3d2e6"]
brights = ["#433f74", "#ff7e70", "#7aed9f", "#ffe8bf", "#92b4ff", "#f284a6", "#64f5c9", "#ffffff"]

[colors.tab_bar]
background = "#1b192f"
inactive_tab_edge = "#1b192f"
inactive_tab_edge_hover = "#1b192f"

[colors.tab_bar.active_tab]
bg_color = "#332e43"
fg_color = "#d3d2e6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1b192f"
fg_color = "#504b88"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#332e43"
fg_color = "#d3d2e6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1b192f"
fg_color = "#504b88"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#332e43"
fg_color = "#d3d2e6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

