[metadata]
name = "Bearded Theme Surprising Watermelon"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c1d9de"
background = "#121f22"
cursor_bg = "#da6c62"
cursor_border = "#da6c62"
cursor_fg = "#142326"
selection_bg = "#4c3734"
selection_fg = "#c1d9de"
scrollbar_thumb = "#28373a"
split = "#091112"
ansi = ["#142326", "#E35535", "#a9dc76", "#da6c62", "#00B3BD", "#c47cbf", "#da6c62", "#c1d9de"]
brights = ["#355c65", "#ff4319", "#a9f65c", "#f75445", "#00b3bd", "#e15fd8", "#f75445", "#ffffff"]

[colors.tab_bar]
background = "#101c1f"
inactive_tab_edge = "#101c1f"
inactive_tab_edge_hover = "#101c1f"

[colors.tab_bar.active_tab]
bg_color = "#142326"
fg_color = "#c1d9de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#101c1f"
fg_color = "#416f79"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#142326"
fg_color = "#c1d9de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#101c1f"
fg_color = "#416f79"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#142326"
fg_color = "#c1d9de"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

