[metadata]
name = "Bearded Theme Arc Reversed"
author = "BeardedBear"
origin_url = "https://github.com/BeardedBear/bearded-theme"

[colors]
foreground = "#c5cdde"
background = "#141924"
cursor_bg = "#EACD61"
cursor_border = "#EACD61"
cursor_fg = "#121721"
selection_bg = "#323b4c"
selection_fg = "#c5cdde"
scrollbar_thumb = "#2a303c"
split = "#0b0e14"
ansi = ["#121721", "#E35535", "#3CEC85", "#EACD61", "#69C3FF", "#F38CEC", "#22ECDB", "#c5cdde"]
brights = ["#384766", "#ff4319", "#29ff82", "#ffd94c", "#69c3ff", "#ff80f6", "#0fffeb", "#ffffff"]

[colors.tab_bar]
background = "#161c28"
inactive_tab_edge = "#161c28"
inactive_tab_edge_hover = "#161c28"

[colors.tab_bar.active_tab]
bg_color = "#121721"
fg_color = "#c5cdde"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#161c28"
fg_color = "#445679"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#121721"
fg_color = "#c5cdde"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#161c28"
fg_color = "#445679"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#121721"
fg_color = "#c5cdde"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

