[workspace]
pane_format = "{session}{if tab} | {tab}{endif}{if pane} | {pane}{endif}"
pane_default = "Workspace"

[tui]
single_click_action = true

[zellij]
pane_frame_style = "titles"
focus_follows_mouse = true
